package tictactoe;

import java.awt.Button;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fmarggra
 */
public class GUI extends javax.swing.JFrame {

    //Variablen
    private int zaehler = -1;
    private Icon kreisIcon = new ImageIcon(GUI.class.getResource(
            "Kreis.png"));
    private Icon kreuzIcon = new ImageIcon(GUI.class.getResource(
            "Kreuz.png"));
    private Icon leerIcon = new ImageIcon(GUI.class.getResource(
            "Leer.png"));

    private int[] buttonIcons;
    private JButton[] buttons;
    private boolean gewonnen = false;

    private int kreuzwin = 0;
    private int kreiswin = 0;
    private int patt = 0;
    private int spielanzahl = 0;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        buttonIcons = new int[10];
        buttons = new JButton[9];
        buttons[0] = button1;
        buttons[1] = button2;
        buttons[2] = button3;
        buttons[3] = button4;
        buttons[4] = button5;
        buttons[5] = button6;
        buttons[6] = button7;
        buttons[7] = button8;
        buttons[8] = button9;
        tictactoefeld.setVisible(false);
        newgame.setVisible(false);
        //kreisuntenrechts.setVisible(true);
        //kreisobenrechts.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jFrame1 = new javax.swing.JFrame();
        tictactoefeld = new javax.swing.JPanel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        spielanzahl1 = new javax.swing.JLabel();
        winskreuz = new javax.swing.JLabel();
        winskreis = new javax.swing.JLabel();
        unentschieden = new javax.swing.JLabel();
        newgame = new javax.swing.JButton();
        feld = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDatei = new javax.swing.JMenu();
        spielstarten1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 0));
        setMinimumSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(null);

        tictactoefeld.setMinimumSize(new java.awt.Dimension(950, 550));
        tictactoefeld.setLayout(null);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button1);
        button1.setBounds(0, 10, 150, 140);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button2);
        button2.setBounds(170, 10, 150, 140);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button3);
        button3.setBounds(340, 10, 150, 140);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button4);
        button4.setBounds(0, 160, 150, 140);

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button5);
        button5.setBounds(170, 170, 150, 140);

        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button7);
        button7.setBounds(0, 320, 150, 140);

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button6);
        button6.setBounds(340, 160, 150, 140);

        button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button8);
        button8.setBounds(160, 320, 150, 140);

        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        tictactoefeld.add(button9);
        button9.setBounds(340, 320, 150, 140);

        spielanzahl1.setFont(new java.awt.Font("DaunPenh", 1, 36)); // NOI18N
        spielanzahl1.setText("Spielanzahl:");
        tictactoefeld.add(spielanzahl1);
        spielanzahl1.setBounds(490, 310, 250, 60);

        winskreuz.setFont(new java.awt.Font("DaunPenh", 1, 36)); // NOI18N
        winskreuz.setText("Kreuz Siege:");
        tictactoefeld.add(winskreuz);
        winskreuz.setBounds(490, 10, 200, 60);

        winskreis.setFont(new java.awt.Font("DaunPenh", 1, 36)); // NOI18N
        winskreis.setText("Kreis Siege:");
        tictactoefeld.add(winskreis);
        winskreis.setBounds(490, 100, 200, 60);

        unentschieden.setFont(new java.awt.Font("DaunPenh", 1, 36)); // NOI18N
        unentschieden.setText("Unentschieden: ");
        tictactoefeld.add(unentschieden);
        unentschieden.setBounds(490, 200, 250, 60);

        newgame.setText("Neues Spiel");
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });
        tictactoefeld.add(newgame);
        newgame.setBounds(500, 390, 200, 80);

        feld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Feld.png"))); // NOI18N
        tictactoefeld.add(feld);
        feld.setBounds(0, 0, 490, 496);

        getContentPane().add(tictactoefeld);
        tictactoefeld.setBounds(0, 0, 730, 500);

        jMenuDatei.setBackground(new java.awt.Color(51, 255, 102));
        jMenuDatei.setText("Datei");

        spielstarten1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        spielstarten1.setBackground(new java.awt.Color(0, 51, 153));
        spielstarten1.setText("TicTacToe starten");
        spielstarten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spielstarten1ActionPerformed(evt);
            }
        });
        jMenuDatei.add(spielstarten1);

        jMenuBar1.add(jMenuDatei);

        jMenu1.setText("Edit");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ermittler
    private int checkicon() {
        if (zaehler % 2 == 0) {
            return 0;
        } else {
            return 1;
        }
    }

    public boolean checkwin() {
        //für kreuz:
        if(! gewonnen){
        if (buttonIcons[1] == 1 && buttonIcons[2] == 1 && buttonIcons[3] == 1
                || buttonIcons[4] == 1 && buttonIcons[5] == 1 && buttonIcons[6] == 1
                || buttonIcons[7] == 1 && buttonIcons[8] == 1 && buttonIcons[9] == 1
                || buttonIcons[1] == 1 && buttonIcons[5] == 1 && buttonIcons[9] == 1
                || buttonIcons[3] == 1 && buttonIcons[5] == 1 && buttonIcons[7] == 1
                || buttonIcons[1] == 1 && buttonIcons[4] == 1 && buttonIcons[7] == 1
                || buttonIcons[2] == 1 && buttonIcons[5] == 1 && buttonIcons[8] == 1
                || buttonIcons[3] == 1 && buttonIcons[6] == 1 && buttonIcons[9] == 1) {
            gewonnen = true;
            kreuzwin++;
            spielanzahl++;
            winskreuz.setText("Kreuz Siege: " + kreuzwin);
            spielanzahl1.setText("Spielanzahl:" + spielanzahl);
            newgame.setVisible(true);
            return true;
        }
        //für kreis
        if (buttonIcons[1] == 2 && buttonIcons[2] == 2 && buttonIcons[3] == 2
                || buttonIcons[4] == 2 && buttonIcons[5] == 2 && buttonIcons[6] == 2
                || buttonIcons[7] == 2 && buttonIcons[8] == 2 && buttonIcons[9] == 2
                || buttonIcons[1] == 2 && buttonIcons[5] == 2 && buttonIcons[9] == 2
                || buttonIcons[3] == 2 && buttonIcons[5] == 2 && buttonIcons[7] == 2
                || buttonIcons[1] == 2 && buttonIcons[4] == 2 && buttonIcons[7] == 2
                || buttonIcons[2] == 2 && buttonIcons[5] == 2 && buttonIcons[8] == 2
                || buttonIcons[3] == 2 && buttonIcons[6] == 2 && buttonIcons[9] == 2) {
            gewonnen = true;
            kreiswin++;
            spielanzahl++;
            newgame.setVisible(true);
            spielanzahl1.setText("Spielanzahl:" + spielanzahl);
            winskreis.setText("Kreis Siege: " + kreiswin);
            return true;
        }
        if (zaehler == 8 && !gewonnen) {
            patt++;
            spielanzahl++;
            gewonnen = true;
            newgame.setVisible(true);
            unentschieden.setText("Unentschieden: " + patt);
            spielanzahl1.setText("Spielanzahl:" + spielanzahl);
        }
        
        }

        return false;
    }

    private Icon getIcon(int id) {
        if (buttonIcons[id] == 1) {
            return kreuzIcon;
        }
        if (buttonIcons[id] == 2) {
            return kreisIcon;
        } else {
            return leerIcon;
        }

    }

    public Icon setIcon(int id) {
        zaehler++;
        if (! gewonnen) {
            if (alreadyUsed(id) == false) {
                if (checkicon() == 0) {
                    buttonIcons[id] = 1;
                    return kreuzIcon;
                } else {
                    buttonIcons[id] = 2;
                    return kreisIcon;
                }
            } else {
                return getIcon(id);
            }
        }
        return getIcon(id);
    }

    private boolean alreadyUsed(int id) {
        if (buttonIcons[id] == 2 || buttonIcons[id] == 1) {
            zaehler--;
            if (zaehler <= -1) {
                zaehler = 0;
            }
            return true;
        } else {
            return false;
        }
    }

    private void spielstarten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spielstarten1ActionPerformed
        tictactoefeld.setVisible(true);
    }//GEN-LAST:event_spielstarten1ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        button9.setIcon(setIcon(9));
        //kreisobenlinks.setVisible(false);
        checkwin();
    }//GEN-LAST:event_button9ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        button1.setIcon(setIcon(1));
        checkwin();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        button2.setIcon(setIcon(2));
        checkwin();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        button3.setIcon(setIcon(3));
        checkwin();
    }//GEN-LAST:event_button3ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        button6.setIcon(setIcon(6));
        checkwin();
    }//GEN-LAST:event_button6ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        button5.setIcon(setIcon(5));
        checkwin();
    }//GEN-LAST:event_button5ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        button4.setIcon(setIcon(4));
        checkwin();
    }//GEN-LAST:event_button4ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        button7.setIcon(setIcon(7));
        checkwin();
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        button8.setIcon(setIcon(8));
        checkwin();
    }//GEN-LAST:event_button8ActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // TODO add your handling code here:
        for (int j = 0; j < buttonIcons.length; j++) {
            buttons[0].setIcon(leerIcon);
            buttons[1].setIcon(leerIcon);
            buttons[2].setIcon(leerIcon);
            buttons[3].setIcon(leerIcon);
            buttons[4].setIcon(leerIcon);
            buttons[5].setIcon(leerIcon);
            buttons[6].setIcon(leerIcon);
            buttons[7].setIcon(leerIcon);
            buttons[8].setIcon(leerIcon);
            zaehler = -1;
            buttonIcons[j] = 0;
            gewonnen = false;
            newgame.setVisible(false);
        }
    }//GEN-LAST:event_newgameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JLabel feld;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDatei;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton newgame;
    private javax.swing.JLabel spielanzahl1;
    private javax.swing.JMenuItem spielstarten1;
    private javax.swing.JPanel tictactoefeld;
    private javax.swing.JLabel unentschieden;
    private javax.swing.JLabel winskreis;
    private javax.swing.JLabel winskreuz;
    // End of variables declaration//GEN-END:variables
}
