package tictactoe;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fmarggra
 */
public class GUI extends javax.swing.JFrame {

    
    final Icon icon1 = new ImageIcon(GUI.class.getResource(
                "Kreis.png"));
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        kreisuntenrechts.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jFrame1 = new javax.swing.JFrame();
        tictactoefeld = new javax.swing.JPanel();
        kreisuntenrechts = new javax.swing.JButton();
        feld = new javax.swing.JLabel();
        kreisobenlinks = new javax.swing.JButton();
        kreisoben = new javax.swing.JButton();
        kreisobenrechts = new javax.swing.JButton();
        kreismitterechts = new javax.swing.JButton();
        kreismitte = new javax.swing.JButton();
        kreismittelinks = new javax.swing.JButton();
        kreisuntenlinks = new javax.swing.JButton();
        kreisunten = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDatei = new javax.swing.JMenu();
        spielstarten1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 0));
        setMinimumSize(new java.awt.Dimension(510, 550));
        getContentPane().setLayout(null);

        tictactoefeld.setLayout(null);

        kreisuntenrechts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreisuntenrechts.setActionCommand("");
        kreisuntenrechts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreisuntenrechtsActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreisuntenrechts);
        kreisuntenrechts.setBounds(340, 320, 150, 140);

        feld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Feld.png"))); // NOI18N
        tictactoefeld.add(feld);
        feld.setBounds(0, 0, 490, 496);

        kreisobenlinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreisobenlinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreisobenlinksActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreisobenlinks);
        kreisobenlinks.setBounds(0, 10, 150, 140);

        kreisoben.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreisoben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreisobenActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreisoben);
        kreisoben.setBounds(170, 10, 150, 140);

        kreisobenrechts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreisobenrechts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreisobenrechtsActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreisobenrechts);
        kreisobenrechts.setBounds(340, 10, 150, 140);

        kreismitterechts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreismitterechts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreismitterechtsActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreismitterechts);
        kreismitterechts.setBounds(340, 160, 150, 140);

        kreismitte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreismitte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreismitteActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreismitte);
        kreismitte.setBounds(170, 170, 150, 140);

        kreismittelinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreismittelinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreismittelinksActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreismittelinks);
        kreismittelinks.setBounds(0, 160, 150, 140);

        kreisuntenlinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreisuntenlinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreisuntenlinksActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreisuntenlinks);
        kreisuntenlinks.setBounds(0, 320, 150, 140);

        kreisunten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Leer.png"))); // NOI18N
        kreisunten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreisuntenActionPerformed(evt);
            }
        });
        tictactoefeld.add(kreisunten);
        kreisunten.setBounds(160, 320, 150, 140);

        getContentPane().add(tictactoefeld);
        tictactoefeld.setBounds(0, 0, 490, 496);

        jMenuDatei.setBackground(new java.awt.Color(51, 255, 102));
        jMenuDatei.setText("Datei");

        spielstarten1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        spielstarten1.setBackground(new java.awt.Color(0, 51, 153));
        spielstarten1.setText("TicTacToe starten");
        spielstarten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spielstarten1ActionPerformed(evt);
            }
        });
        jMenuDatei.add(spielstarten1);

        jMenuBar1.add(jMenuDatei);

        jMenu1.setText("Edit");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spielstarten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spielstarten1ActionPerformed
        System.out.println("Hallo welt");
    }//GEN-LAST:event_spielstarten1ActionPerformed

    private void kreisuntenrechtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreisuntenrechtsActionPerformed
        kreisuntenrechts.setIcon(icon1);
        //kreisobenlinks.setVisible(false);
    }//GEN-LAST:event_kreisuntenrechtsActionPerformed

    private void kreisobenlinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreisobenlinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreisobenlinksActionPerformed

    private void kreisobenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreisobenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreisobenActionPerformed

    private void kreisobenrechtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreisobenrechtsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreisobenrechtsActionPerformed

    private void kreismitterechtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreismitterechtsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreismitterechtsActionPerformed

    private void kreismitteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreismitteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreismitteActionPerformed

    private void kreismittelinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreismittelinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreismittelinksActionPerformed

    private void kreisuntenlinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreisuntenlinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreisuntenlinksActionPerformed

    private void kreisuntenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreisuntenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreisuntenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel feld;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDatei;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton kreismitte;
    private javax.swing.JButton kreismittelinks;
    private javax.swing.JButton kreismitterechts;
    private javax.swing.JButton kreisoben;
    private javax.swing.JButton kreisobenlinks;
    private javax.swing.JButton kreisobenrechts;
    private javax.swing.JButton kreisunten;
    private javax.swing.JButton kreisuntenlinks;
    private javax.swing.JButton kreisuntenrechts;
    private javax.swing.JMenuItem spielstarten1;
    private javax.swing.JPanel tictactoefeld;
    // End of variables declaration//GEN-END:variables
}
